//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Northwind.ORM.Main.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers : IValidatableObject
    {
        [Required(ErrorMessage = "CustomerID is een verplicht veld")]
        public string CustomerID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (CustomerID.StartsWith("XX"))
            {
                yield return new ValidationResult("CustomerID cannot start with XX", new[] {"CustomerID", "XX"});
            }
        }
    }
}
